# Generated by Django 5.1.6 on 2025-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_interested',
            name='numOfTimes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
