# Generated by Django 5.1.6 on 2025-02-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_interested_numoftimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_interested',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='user_interested',
            old_name='product_id',
            new_name='product',
        ),
    ]
